// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

var MyLambdaFunction = require('../src/index.js'); // assumes single Lambda function with exports.handler

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
var event =
    {
      "session": {
        "new": true,
        "sessionId": "SessionId.e14dfc6c-0dae-4212-a83e-383b5abda77e",
        "application": {
          "applicationId": "amzn1.ask.skill.e4f39f24-69e8-4166-87fd-88281166e588"
        },
        "attributes": {},
        "user": {
          "userId": "amzn1.ask.account.MARKCARPENTERTESTINGTHISSKILLWITHOUTPUSHINGTOLAMDBAFIRSTOMGISTHISWONDERFUL"
        }
      },
      "request": {
        "type": "IntentRequest",
        "requestId": "EdwRequestId.c81fa759-e8c8-47c0-b7a9-f59b268bde1d",
        "intent": {
          "name": "TellMeAboutIntent",
          "slots": {
            "TheNumber": {
              "name": "TheNumber",
              "value": "13343433"
            }
          }
        },
        "locale": "en-US",
        "timestamp": "2017-10-03T15:28:30Z"
      },
      "context": {
        "AudioPlayer": {
          "playerActivity": "IDLE"
        },
        "System": {
          "application": {
            "applicationId": "amzn1.ask.skill.e4f39f24-69e8-4166-87fd-88281166e588"
          },
          "user": {
            "userId": "amzn1.ask.account.MARKCARPENTERTESTINGTHISSKILLWITHOUTPUSHINGTOLAMDBAFIRSTOMGISTHISWONDERFUL"
          },
          "device": {
            "supportedInterfaces": {}
          }
        }
      },
      "version": "1.0"
};

var context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
